config/routes.rb
SampleApp::Application.routes.draw do
  
  get "users/new"
 match '/signup', :to => 'users#new'

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def contact
  @title = "Contact"
  end
 
  def about
  	@title = "About"
  end

 def help
  	@title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@title = "Sign Up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logo
	image_tag("rails.png", :alt => "sample app", :class => "round") 
    end
     
	#Return a title on per page basis
	def title 
		base_title = "Ruby on Rails Sample App"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
    end
 end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
 <nav class='round'>
 	<ul>
 	  <li><%= link_to "About", about_path %></li>
 	  <li><%= link_to "Contact", contact_path %></li>
 	  <li><%= link_to "News", '#' %></li>
 	  <li><%= link_to "Rails tutorial", '#' %></li>
 	</ul>
 	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
			<nav class="round">
				<ul>
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sign In", '#'%></li>
				</ul>
			</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>	
	   <%= render 'layouts/stylesheets' %>
	</head>	
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				 <%= yield %>
			</section>
			<%= render 'layouts/footer' %>
     </div>
	</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>This is the About Page</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>find our contact details</p>

app/views/pages/help.html.erb
<h1>Get Help Here</h1>
<p>This is the Help Page</p>

app/views/pages/home.html.erb
<h1>Sample APP</h1>
<p>This is the Home Page</p>

<%= link_to "Sign up now!", '/signup', :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>